spring:
  application:
    name: payr-email-api

kafka:
  bootstrap-servers: 'broker:29092'

payr:
  kafka:
    topic-orders-new: orders.new
    topic-orders-error: orders.error
    topic-notification-new: notification.new
    topic-update-user: user.update
    topic-email-register: email.register